# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/pkgpurl.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#literate-programming` for more information on the literature programming approach used applying the R Markdown format.

utils::globalVariables(names = ".")

#' Purl `Rmd/*.Rmd` to `R/*-GEN.R`
#'
#' This function strives to provide a standardized way to convert all `.Rmd` files in the `Rmd/` directory to bare `.R` files in the directory `R/` using
#' [knitr::purl()].
#'
#' The generated `.R` files will be named the same as the `.Rmd` files plus the suffix `-GEN` to indicate the file was auto-generated. So the file
#' `Rmd/foo.Rmd` for example will be converted to `R/foo-GEN.R`.
#'
#' The [R Markdown file format](https://rmarkdown.rstudio.com/) allows to write code in the
#' [literate programming](https://en.wikipedia.org/wiki/Literate_programming) way. So you can intermingle code with related prose in
#' [Markdown syntax](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html) optimized for human readability instead of having to
#' rely on [`#` comments](https://cran.r-project.org/doc/manuals/r-release/R-intro.html#R-commands_003b-case-sensitivity-etc) only. It also allows you to
#' easily compile your source code to beautifully looking HTML, PDF etc. files.
#'
#' @param pkg_dir The path to the root of the package directory.
#'
#' @export
purl_rmd <- function(pkg_dir = ".") {
  
  rmd_dir <- fs::path_abs(pkg_dir, "Rmd/")
  
  if (fs::dir_exists(rmd_dir)) {
    
    rmd_files <- fs::dir_ls(path = rmd_dir,
                            regexp = "Rmd/[^/]+\\.[Rr]md")
    
    if (length(rmd_files) > 0) {
      
      rmd_files %>% purrr::walk(process_rmd)
      
    } else {
      
      rlang::warn(glue::glue("`{pkg_dir}` does not appear to be an Rmd package directory. Nothing done."))
    }
  }
}

# helper function purling a single file `Rmd/*.Rmd` to `R/*-GEN.R`
process_rmd <- function(rmd) {
  
  output <- rmd %>% stringr::str_replace(pattern = "Rmd/([^/]+)\\.[Rr]md$",
                                         replacement = "R/\\1-GEN.R")
  
  knitr::purl(input = rmd,
              output = output,
              quiet = TRUE,
              documentation = 0)
  
  # add reminder header lines to generated .R files
  rmd %>%
    fs::path_rel(start = fs::path_dir(fs::path_dir(.))) %>%
    paste0("# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `", ., "` and run `pkgpurl::purl_rmd()`.\n",
           "# See `README.md#literate-programming` for more information on the literature programming approach used applying the R Markdown format.\n\n",
           readr::read_file(file = output)) %>%
    readr::write_file(path = output)
}
